JavaScript Object Notation (JSON) is a standard text-based format for representing structured data based on JavaScript object syntax. JSON is a lightweight data format used for data interchange between multiple different languages. It is easy to read for humans and easily parsed by machines. It's pretty common for websites to return JSON from API's so that the information is easy to parse by different programming languages.

SQL(Structured Query Language) is used to manage relational databases, and It is used to perform fetching rows, database creation, modifying databases, deleting databases, and also reading, writing data. It is extremely useful in managing structured data, i.e. data that is used to represent relations among entities and variables. SQL is predicated on relational algebra and tuple relational calculus. MS Access, MySQL is a standard database language.

Working with JSON/SQL involves handling structured data in JSON format or querying relational databases using SQL, essential skills for data manipulation and analysis.

In [1]:
import pandas as pd

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('train.json').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39774 entries, 0 to 39773
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           39774 non-null  int64
 1   cuisine      39774 non-null  object
 2   ingredients  39774 non-null  object
dtypes: int64(1), object(2)
memory usage: 932.3+ KB

In [5]:
# loading json from an api

pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,0.0431
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,0.8230
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,1.0400
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,4.5700
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,1.2600
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,2.8700
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,0.2150
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,0.3110
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2025-05-14,1747180802,0.3150

#### Working with SQL

In [6]:
# this is the required software to extract sql file xampp. Go to its control panel and start the apache server and the mysql server

In [7]:
# go to localhost/phpmyadmin
# create a new database 
# go to import and choose the sql file (keep the database name same as the sql file name)

In [8]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 882.6 kB/s eta 0:00:13
     - ------------------------------------- 0.5/11.9 MB 882.6 kB/s eta 0:00:13
     -- ------------------------------------ 0.8/11.9 MB 932.9 kB/s eta 0:00:12
     --- ----------------------------------- 1.0/11.9 MB 949.8 kB/s eta 0:00:12
     ---- ----------------------------------- 1.3/11.9 MB 1.0 MB/s eta 0:00:11
     ----- ---------------------------------- 1.6/11.9 MB 1.0 MB/s eta 0:00:11
     ------ --------------------------------- 1.8/11.9 MB 1.0 MB/s eta 0:00:10
     ------- -------------------------------- 2.1/11.9 MB 1.1 MB/s eta 0:00:10
     ------- -------------------------------- 2.4/11.9 MB 1.1 MB/s eta 0:00:09
     -------- ------------------------------- 2.6/11.9 MB 1.2 MB/s eta 0:00:09
     --------- ------------------------------ 2.9/11.9 MB 1.1 MB/s eta 0:00:08
     --------- ------------------------------ 2.9/11.9 MB 1.1 MB/s eta 0:00:08
     ---------- ----------------------------- 3.1/11.9 MB 1.0 MB/s eta 0:00:09
     ----------- ---------------------------- 3.4/11.9 MB 1.0 MB/s eta 0:00:09
     ------------- -------------------------- 3.9/11.9 MB 1.1 MB/s eta 0:00:07
     --------------- ------------------------ 4.7/11.9 MB 1.3 MB/s eta 0:00:06
     ------------------ --------------------- 5.5/11.9 MB 1.4 MB/s eta 0:00:05
     ----------------------- ---------------- 6.8/11.9 MB 1.7 MB/s eta 0:00:04
     --------------------------- ------------ 8.1/11.9 MB 1.9 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 2.2 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.5 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=247961 sha256=5251879770178ae4ded3d8560a07b04fe9c00e88773e06c06158e5b567e9aa76
  Stored in directory: c:\users\syed naveed\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import mysql.connector

In [ ]:
# mysql connector doesn't support the new password authentication so it won't work

# use pymysql

mysql.connector.connect(host='localhost',user='root', password='MySQL@009', database='world')

NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported